using System;
using Microsoft.SharePoint;


namespace ETQuickViewVisualWebPart
{
    public class LoadQueryData
    {
        public void AddData(SPWeb web)        {
            
            SPList list = web.Lists.TryGetList("QuickViewQueries");
            String viewFields1 = "\"<FieldRef Name='Closed_x0020_Out' /><FieldRef Name='CurrentStatus1'/><FieldRef Name='Urgent'/><FieldRef Name='Created'/><FieldRef Name='Author'/><FieldRef Name='Ticket_x0020_Status'/><FieldRef Name='ID'/><FieldRef Name='Title'/><FieldRef Name='ServerUrl'/><FieldRef Name='FileRef'/><ListProperty Name='Title'/>\"";
            // Changed 3/6/2014
            if (list != null)
            {
                addItem(list, "Business Cards", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Data Backup", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Facility Work Order", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Foreign Visitor Request", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "General Graphics", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "General IT Issues", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Visitor Request - US Citizen", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Visitor Authorization Request via JPAS", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "SoftwareRequestVersion2", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Restricted Access", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "SharePoint Access", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Reset Voicemail", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "PropertyPassReplacement", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Printer Station Maintenance", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Printer Install", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Office Move", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Overseas Travel - Personal", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Overseas Travel - Business Related - Version 3", "Waiting_for_ApprovalManagement", "\"<FieldRef Name='Closed_x0020_Out' /><FieldRef Name='CurrentStatus1'/><FieldRef Name='Urgent'/><FieldRef Name='Created'/><FieldRef Name='Author'/> <FieldRef Name='Ticket_x0020_Status'/><FieldRef Name='ID'/><FieldRef Name='Title'/><FieldRef Name='EncodedAbsUrl'/><FieldRef Name='FileRef'/><ListProperty Name='Title'/><FieldRef Name='NewItemReady' /><FieldRef Name='Step1Approved' /><FieldRef Name='Step1Ready' /><FieldRef Name='Step2Approved' /><FieldRef Name='Step3Ready' /><FieldRef Name='Step5Approved' /><FieldRef Name='Step5Ready' /><FieldRef Name='Step6Approved' />\"", "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><And><Or><And><Or><And><Or><And><Eq><FieldRef Name='NewItemReady' /><Value Type='Choice'>Yes</Value></Eq><Eq><FieldRef Name='Step1Approved' /><Value Type='Choice'>None</Value></Eq></And><Eq><FieldRef Name='Step1Ready' /><Value Type='Choice'>Yes</Value></Eq></Or><Eq><FieldRef Name='Step2Approved' /><Value Type='Choice'>None</Value></Eq></And><Eq><FieldRef Name='Step3Ready' /><Value Type='Choice'>Yes</Value></Eq></Or><Eq><FieldRef Name='Step5Approved' /><Value Type='Choice'>None</Value></Eq></And><Eq><FieldRef Name='Step5Ready' /><Value Type='Choice'>Yes</Value></Eq></Or><Eq><FieldRef Name='Step6Approved' /><Value Type='Choice'>None</Value></Eq></And></And></Where>\"");
                addItem(list, "Office Supplies", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "News Article Request", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "MiFi Checkout", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "IT Equipment Requests", "Waiting_for_ApprovalManagement", viewFields1, "\"<Where><And><Eq><FieldRef Name='NewItemReady' /><Value Type='Choice'>Yes</Value></Eq><Eq><FieldRef Name='Approved_x003f_' /><Value Type='Choice'>None</Value></Eq></And></Where>\"");
                addItem(list, "General Security Request", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "General Phone Issues", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Key Replacement", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");
                addItem(list, "Shipping Ticket", "Waiting_for_ApprovalManagement", viewFields1, "\"<Where><And><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Eq><FieldRef Name='ReadyStep1' /><Value Type='Choice'>Yes</Value></Eq></And><Or><Eq><FieldRef Name='ManagerApproval' /><Value Type='Choice'>None</Value></Eq><Eq><FieldRef Name='BudgetApproved' /><Value Type='Choice'>None</Value></Eq></Or></And></Where>\"");
                addItem(list, "Shipping Ticket", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><And><Or><And><Eq><FieldRef Name='NewItemReady' /><Value Type='Choice'>Yes</Value></Eq><Eq><FieldRef Name='ReadyStep1' /><Value Type='Choice'>No</Value></Eq></And><Eq><FieldRef Name='ReadyStep3' /><Value Type='Choice'>Yes</Value></Eq></Or><Eq><FieldRef Name='ReadyStep4' /><Value Type='Choice'>No</Value></Eq></And></And></Where>\"");
                addItem(list, "SoftwareRequestVersion2", "Waiting_for_ApprovalManagement", viewFields1, "\"<Where><And><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Eq><FieldRef Name='NewItemReady' /><Value Type='Choice'>Yes</Value></Eq></And><Eq><FieldRef Name='Approved' /><Value Type='Choice'>None</Value></Eq></And></Where>\"");
                addItem(list, "Overseas Travel - Business Related - Version 3", "Waiting_for_Leadership", "\"<FieldRef Name='Urgent'/><FieldRef Name='Created'/><FieldRef Name='Author'/><FieldRef Name='CurrentStatus1'/><FieldRef Name='Ticket_x0020_Status'/><FieldRef Name='ID'/><FieldRef Name='Title'/><FieldRef Name='EncodedAbsUrl'/><FieldRef Name='FileRef'/><ListProperty Name='Title'/><FieldRef Name='Step2Ready' /><FieldRef Name='Step3Ready' /><FieldRef Name='Step7Ready' /><FieldRef Name='Closed_x0020_Out' />\"", "\"<Where><Or><And><Eq><FieldRef Name='Step2Ready' /><Value Type='Choice'>Yes</Value></Eq><Eq><FieldRef Name='Step3Ready' /><Value Type='Choice'>No</Value></Eq></And><And><Eq><FieldRef Name='Step7Ready' /><Value Type='Choice'>Yes</Value></Eq><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq></And></Or></Where>\"");
                addItem(list, "Office Move", "Waiting_for_ApprovalManagement", viewFields1, "\"<Where><And><Eq><FieldRef Name='NewItemReady' /><Value Type='Choice'>Yes</Value></Eq><Eq><FieldRef Name='Supervisor_x0020_Approval' /><Value Type='Choice'>None</Value></Eq></And></Where>\"");
                addItem(list, "IT Equipment Requests", "Waiting_for_Leadership", viewFields1, "\"<Where><And><Eq><FieldRef Name='Closed_x0020_Out' /><Value Type='Choice'>No</Value></Eq><Or><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>Acknowledged</Value></BeginsWith><BeginsWith><FieldRef Name='Ticket_x0020_Status' /><Value Type='Choice'>New</Value></BeginsWith></Or></And></Where>\"");

            }
        }


        private static void addItem(SPList list, string title, string queryType, string viewFields, string query)
        {
            SPListItem item = list.Items.Add();
            item["Title"] = title;
            item["QueryType"] = queryType;
            item["ViewFields"] = viewFields;
            item["Query"] = query;
            item.Update();
        }
    }
}
